server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatisplus?useSSL=false&serverTimezone=UTC
    username: root
    password: 123
logging:
  level:
    org.suda: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除字段名，配置后可以不用@TableLogic注解
      logic-delete-value: 1
      logic-not-delete-value: 0